version: '3.8'

services:
  postgres-container:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: students_db
    networks:
      - app_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/migrations   # Correctly mounting 'migrations' folder

  api-container:
    build: .
    environment:
      DATABASE_URL: "postgresql://admin:admin@postgres-container:5432/students_db"
    ports:
      - "5000:5000"
    networks:
      - app_network
    depends_on:
      - postgres-container

networks:
  app_network:

volumes:
  postgres_data:
