name: CI Pipeline

on:
  push:
    paths:
      - 'app/**'       # Trigger only when code changes in the 'app' folder
      - 'Makefile'      # Trigger if Makefile changes
      - 'Dockerfile'    # Trigger if Dockerfile changes
  workflow_dispatch:    # Allows manual triggering of the pipeline

jobs:
  build-and-deploy:
    runs-on: self-hosted  # Uses your self-hosted runner

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 2: Install dependencies (with virtual environment)
      - name: Install Dependencies
        run: |
          python3 -m venv venv         # Create a virtual environment
          source venv/bin/activate     # Activate the virtual environment
          pip install -r requirements.txt
          echo "VENV PATH=$(pwd)/venv/bin" >> $GITHUB_ENV
          make install_tools

      # Step 3: Build the API
      - name: Build API
        run: make build

  docker-build-push:
    runs-on: self-hosted
    needs: build-and-deploy  # Ensures build steps are successful before proceeding

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # Step 4: Login to DockerHub
      - name: Docker Login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      # Step 5: Build and Push Docker Image
      - name: Build and Push Docker Image
        run: |
          docker build -t gauravhalnawar0506/api-dev-env-setup-sre-bootcamp:latest .
          docker push gauravhalnawar0506/api-dev-env-setup-sre-bootcamp:latest
